var bg;
var mariofont;

var name= ["Jacob",
    "Michael",
    "Joshua",
    "Matthew",
    "Daniel",
    "Christopher",
    "Andrew",
    "Ethan",
    "Joseph",
    "William",
    "Anthony",
    "David",
    "Alexander",
    "Nicholas",
    "Ryan",
    "Tyler",
    "James",
    "John",
    "Jonathan",
    "Noah",
    "Brandon",
    "Christian",
    "Dylan",
    "Samuel",
    "Benjamin",
    "Nathan",
    "Zachary",
    "Logan",
    "Justin",
    "Gabriel",
    "Jose",
    "Austin",
    "Kevin",
    "Elijah",
    "Caleb",
    "Robert",
    "Thomas",
    "Jordan",
    "Cameron",
    "Jack",
    "Hunter",
    "Jackson",
    "Angel",
    "Isaiah",
    "Evan",
    "Isaac",
    "Luke",
    "Mason",
    "Jason",
    "Jayden",
    "Gavin",
    "Aaron",
    "Connor",
    "Aiden",
    "Aidan",
    "Kyle",
    "Juan",
    "Charles",
    "Luis",
    "Adam",
    "Lucas",
    "Brian",
    "Eric",
    "Adrian",
    "Nathaniel",
    "Sean",
    "Alex",
    "Carlos",
    "Ian",
    "Bryan",
    "Owen",
    "Jesus",
    "Landon",
    "Julian",
    "Chase",
    "Cole",
    "Diego",
    "Jeremiah",
    "Steven",
    "Sebastian",
    "Xavier",
    "Timothy",
    "Carter",
    "Wyatt",
    "Brayden",
    "Blake",
    "Hayden",
    "Devin",
    "Cody",
    "Richard",
    "Seth",
    "Dominic",
    "Jaden",
    "Antonio",
    "Miguel",
    "Liam",
    "Patrick",
    "Carson",
    "Jesse",
    "Tristan",
    "Alejandro",
    "Henry",
    "Victor",
    "Trevor",
    "Bryce",
    "Jake",
    "Riley",
    "Colin",
    "Jared",
    "Jeremy",
    "Mark",
    "Caden",
    "Garrett",
    "Parker",
    "Marcus",
    "Vincent",
    "Kaleb",
    "Kaden",
    "Brady",
    "Colton",
    "Kenneth",
    "Joel",
    "Oscar",
    "Josiah",
    "Jorge",
    "Cooper",
    "Ashton",
    "Tanner",
    "Eduardo",
    "Paul",
    "Edward",
    "Ivan",
    "Preston",
    "Maxwell",
    "Alan",
    "Levi",
    "Stephen",
    "Grant",
    "Nicolas",
    "Omar",
    "Dakota",
    "Alexis",
    "George",
    "Collin",
    "Eli",
    "Spencer",
    "Gage",
    "Max",
    "Cristian",
    "Ricardo",
    "Derek",
    "Micah",
    "Brody",
    "Francisco",
    "Nolan",
    "Ayden",
    "Dalton",
    "Shane",
    "Peter",
    "Damian",
    "Jeffrey",
    "Brendan",
    "Travis",
    "Fernando",
    "Peyton",
    "Conner",
    "Andres",
    "Javier",
    "Giovanni",
    "Shawn",
    "Braden",
    "Jonah",
    "Bradley",
    "Cesar",
    "Emmanuel",
    "Manuel",
    "Edgar",
    "Mario",
    "Erik",
    "Edwin",
    "Johnathan",
    "Devon",
    "Erick",
    "Wesley",
    "Oliver",
    "Trenton",
    "Hector",
    "Malachi",
    "Jalen",
    "Raymond",
    "Gregory",
    "Abraham",
    "Elias",
    "Leonardo",
    "Sergio",
    "Donovan",
    "Colby",
    "Marco",
    "Bryson",
    "Martin",
    "Emily",
    "Madison",
    "Emma",
    "Olivia",
    "Hannah",
    "Abigail",
    "Isabella",
    "Samantha",
    "Elizabeth",
    "Ashley",
    "Alexis",
    "Sarah",
    "Sophia",
    "Alyssa",
    "Grace",
    "Ava",
    "Taylor",
    "Brianna",
    "Lauren",
    "Chloe",
    "Natalie",
    "Kayla",
    "Jessica",
    "Anna",
    "Victoria",
    "Mia",
    "Hailey",
    "Sydney",
    "Jasmine",
    "Julia",
    "Morgan",
    "Destiny",
    "Rachel",
    "Ella",
    "Kaitlyn",
    "Megan",
    "Katherine",
    "Savannah",
    "Jennifer",
    "Alexandra",
    "Allison",
    "Haley",
    "Maria",
    "Kaylee",
    "Lily",
    "Makayla",
    "Brooke",
    "Nicole",
    "Mackenzie",
    "Addison",
    "Stephanie",
    "Lillian",
    "Andrea",
    "Zoe",
    "Faith",
    "Kimberly",
    "Madeline",
    "Alexa",
    "Katelyn",
    "Gabriella",
    "Gabrielle",
    "Trinity",
    "Amanda",
    "Kylie",
    "Mary",
    "Paige",
    "Riley",
    "Leah",
    "Jenna",
    "Sara",
    "Rebecca",
    "Michelle",
    "Sofia",
    "Vanessa",
    "Jordan",
    "Angelina",
    "Caroline",
    "Avery",
    "Audrey",
    "Evelyn",
    "Maya",
    "Claire",
    "Autumn",
    "Jocelyn",
    "Ariana",
    "Nevaeh",
    "Arianna",
    "Jada",
    "Bailey",
    "Brooklyn",
    "Aaliyah",
    "Amber",
    "Isabel",
    "Mariah",
    "Danielle",
    "Melanie",
    "Sierra",
    "Erin",
    "Molly",
    "Amelia",
    "Isabelle",
    "Madelyn",
    "Melissa",
    "Jacqueline",
    "Marissa",
    "Shelby",
    "Angela",
    "Leslie",
    "Katie",
    "Jade",
    "Catherine",
    "Diana",
    "Aubrey",
    "Mya",
    "Amy",
    "Briana",
    "Sophie",
    "Gabriela",
    "Breanna",
    "Gianna",
    "Kennedy",
    "Gracie",
    "Peyton",
    "Adriana",
    "Christina",
    "Courtney",
    "Daniela",
    "Lydia",
    "Kathryn",
    "Valeria",
    "Layla",
    "Alexandria",
    "Natalia",
    "Angel",
    "Laura",
    "Charlotte",
    "Margaret",
    "Cheyenne",
    "Mikayla",
    "Miranda",
    "Naomi",
    "Kelsey",
    "Payton",
    "Ana",
    "Alicia",
    "Jillian",
    "Daisy",
    "Mckenzie",
    "Ashlyn",
    "Sabrina",
    "Caitlin",
    "Summer",
    "Ruby",
    "Rylee",
    "Valerie",
    "Skylar",
    "Lindsey",
    "Kelly",
    "Genesis",
    "Zoey",
    "Eva",
    "Sadie",
    "Alexia",
    "Cassidy",
    "Kylee",
    "Kendall",
    "Jordyn",
    "Kate",
    "Jayla",
    "Karen",
    "Tiffany",
    "Cassandra",
    "Juliana",
    "Reagan",
    "Caitlyn",
    "Giselle",
    "Serenity",
    "Alondra",
    "Lucy",
    "Bianca",
    "Kiara",
    "Crystal",
    "Erica",
    "Angelica",
    "Hope",
    "Chelsea",
    "Alana",
    "Liliana",
    "Brittany",
    "Camila",
    "Makenzie",
    "Lilly",
    "Veronica",
    "Abby",
    "Jazmin",
    "Adrianna",
    "Delaney",
    "Karina",
    "Ellie",
    "Jasmin"
  ]




var princess = ["hero",
"analyst",
"reasoner",
"bureaucrat",
"lawyer",
"accountant",
"politician",
"manager",
"caretaker",
"doctor",
"healer",
"nurse",
"catalyst",
"coward",
"curmudgeon",
"grump",
"mentor",
"elder",
"teacher",
"professor",
"parent",
"shaman",
"guide",
"soothsayer",
"expositor",
"hierophant",
"trickster",
"shapeshifter",
"magician",
"devil",
"fool",
"joker",
"jester",
"idiot",
"child",
"innocent",
"virgin",
"youth",
"ingenue",
"self",
"mirror-image",
"hermit",
"loner",
"introvert",
"wanderer",
"traveler",
"explorer",
"hunter",
"seeker",
"tracker",
"inspector",
"judge",
"justice",
"magistrate",
"arbiter",
"sheriff",
"referee",
"examiner",
"weaver",
"creator",
"spinner",
"death",
"executioner",
"giver",
"benefactor",
"superhuman",
"dreamer",
"thinker",
"gossip",
"tattletale",
"whisperer",
"communicator",
"guardian",
"protector",
"hedonist",
"pleasure-seeker",
"leader",
"captain",
"general",
"martyr",
"everyman",
"poet",
"bard",
"singer",
"philosopher",
"rebel",
"rogue",
"outsider",
"fighter",
"slave",
"captive",
"laborer",
"samaritan",
"scholar",
"didact",
"academic",
"learner",
"survivor",
"escapee",
"sycophant",
"yes-man",
"temptress",
"seductress",
"tyrant",
"bully",
"victim",
"target",
"sufferer",
"waif",
"weakling",
"ragamuffin",
"urchin",
"minion",
"lackey",
"worker",
"employee",
"princess",
"queen",
"king",
"prince"
]

var location = [
    "Aquarium",
    "Arcade",
    "Art Gallery",
    "Bowling Alley",
    "Casino",
    "circus",
    "Comedy Club",
    "Concert Hall",
    "Country Dance Club",
    "Disc Golf",
    "General Entertainment",
    "Go Kart Track",
    "Historic Site",
    "Laser Tag",
    "Mini Golf",
    "Movie Theater",
    "Art Museum",
    "History Museum"
    "Planetarium",
    "Science Museum",
    "Music Venue",
    "Jazz Club",
    "Piano Bar",
    "Rock Club",
    "Outdoor Sculpture",
    "Performing Arts Venue",
    "Dance Studio",
    "Indie Theater",
    "Opera House"
    "Theater",
    "Pool Hall",
    "Public Art",
    "Racetrack",
    "Roller Rink",
    "Salsa Club",
    "Stadium",
    "Baseball Stadium",
    "Basketball Stadium",
    "Cricket Ground",
    "Football Stadium",
    "Hockey Arena",
    "Soccer Stadium",
    "Tennis Court",
    "Track Field",
    "Street Art Installation",
    "Theme Park",
    "Water Park",
    "Zoo",
    "Academic Building",
    "Dorm",
    "Administrative Building",
    "Corporate Office",
    "Auditorium",
    "Bookstore",
    "Cafeteria",
    "Classroom",
    "Gym",
    "Lab",
    "Library",
    "Recreation Center",
    "Residence Hall",
    "Community College",
    "Fraternity House",
    "Law School",
    "Sorority House",
    "Medical School",
    "Student Center",
    "Trade School",
    "University",
    "Event",
    "Conference",
    "Convention",
    "Festival",
    "Music Festival",
    "Parade",
    "Stoop Sale",
    "Street Fair",
    "Afghan Restaurant",
    "African Restaurant",
    "American Restaurant",
    "Arepa Restaurant",
    "Argentinian Restaurant",
    "Asian Restaurant",
    "Australian Restaurant",
    "Austrian Restaurant",
    "BBQ Joint",
    "Bagel Shop",
    "Bakery",
    "Belarusian Restaurant",
    "Belgian Restaurant",
    "Bistro",
    "Brazilian Restaurant",
    "Breakfast Spot",
    "Bubble Tea Shop",
    "Buffet",
    "Burger Joint",
    "Burrito Place",
    "Café",
    "Cajun Restaurant",
    "Cambodia Restaurant",
    "Caribbean Restaurant",
    "Chinese Restaurant",
    "Coffee Shop",
    "Creperie",
    "Cuban Restaurant",
    "Cupcake Shop",
    "Czech Restaurant",
    "Deli",
    "Bodega",
    "Dessert Shop",
    "Dim Sum Restaurant",
    "Diner",
    "Distillery",
    "Donut Shop",
    "Dumpling Restaurant",
    "British Restaurant",
    "Ethiopian Restaurant",
    "Falafel Restaurant",
    "Fast Food Place",
    "Fish & Chips Shop",
    "Fondue Restaurant",
    "Food Truck",
    "French Restaurant",
    "Fried Chicken Joint",
    "Gastropub",
    "German Beer Hall",
    "Gluten-Free Restaurant",
    "Greek Restaurant",
    "Halal Restaurant",
    "Hawaiian Restaurant",
    "Himalayan Restaurant",
    "Hot Dog Cart",
    "Korean BBQ",
    "Ice Cream Shop",
    "Indian Buffet",
    "Indonesian Restaurant",
    "Irish Pub",
    "Italian Restaurant",
    "Japanese Restaurant",
    "Sushi Restaurant",
    "Jewish Deli",
    "Juice Bar",
    "Korean Restaurant",
    "Mac & Cheese Joint",
    "Malaysian Restaurant",
    "Mediterranean Restaurant",
    "Mexican Restaurant",
    "Middle Eastern Restaurant",
    "Molecur Gastronomy Restaurant",
    "Mongolian Restaurant",
    "Moroccan Restaurant",
    "Museum of Jurassic Technology",
    "Pakistani Restaurant",
    "Persian Restaurant",
    "Peruvian Restaurant",
    "Pie Shop",
    "Pizza Place",
    "Polish Restaurant",
    "Ramen Shop",
    "Noodle House",
    "Russian Restaurant",
    "Hungarian Restaurant",
    "Romanian Restaurant",
    "Salad Shop",
    "Sandwich Place",
    "Scandinavian Restaurant",
    "Seafood Restaurant",
    "Snack Place",
    "Soup Place",
    "Southern Restaurant",
    "Soul Food Restaurant",
    "Souvlaki Shop",
    "Spanish Restaurant",
    "Steakhouse",
    "Swiss Restaurant",
    "Taco Shop",
    "Tapas Restaurant",
    "Tea Room",
    "Thai Restaurant",
    "Pho Soup Shop",
    "Turkish Restaurant",
    "Ukrainian Restaurant",
    "Vegetarian Restaurant",
    "Vegan Restaurant",
    "Vietnamese Restaurant",
    "Winery",
    "Wing Joint",
    "Frozen Yogurt Shop",
    "Bar",
    "Beach Bar",
    "Beer Garden",
    "Brewery",
    "Champagne Bar",
    "Cocktail Bar",
    "Dive Bar",
    "Gay Bar",
    "Hookah Bar",
    "Hotel Bar",
    "Karaoke Bar",
    "Lounge",
    "Night Market",
    "Nightclub",
    "Pub",
    "Sake Bar",
    "Speakeasy",
    "Sports Bar",
    "Strip Club",
    "Whiskey Bar",
    "Wine Bar",
    "Badminton Court",
    "Baseball Field",
    "Basketball Court", 
    "Bowling Green",
    "Golf Course",
    "Hockey Field",
    "Paintball Field",
    "Rugby Pitch",
    "Skate Park",
    "Skating Rink",
    "Soccer Field",
    "Sports Club",
    "Squash Court",
    "Tennis Court",
    "Volleyball Court",
    "Bath House",
    "Bathing Area",
    "Beach"
    "Nude Beach",
    "Surf Spot",
    "Botanical Garden",
    "Bridge",
    "Campground",
    "Castle",
    "Cemetery",
    "Dive Spot",
    "Dog Run",
    "Farm",
    "Field"
    "Fishing Spot",
    "Forest",
    "Garden",
    "Gun Range",
    "Harbor",
    "Marina",
    "Hot Spring",
    "Island",
    "Lake",
    "Lighthouse",
    "Mountain",
    "National Park",
    "Palace",
    "Park",
    "Pedestrian Plaza",
    "Playground",
    "Plaza",
    "Pool",
    "Rafting Spot",
    "River",
    "Rock Climbing Gym",
    "Scenic Lookout",
    "Sculpture Garden",
    "Ski Village",
    "Horse Stable",
    "City",
    "County",
    "Country",
    "Neighborhood",
    "State",
    "Town",
    "Nation",
    "Village",
    "Summer Camp",
    "Trail",
    "Tree",
    "Vineyard",
    "Volcano",
    "Well",
    "Animal Shelter",
    "Auditorium",
    "Building",
    "Club House",
    "Community Center",
    "Convention Center",
    "Meeting Room",
    "Cultural Center",
    "Distribution Center",
    "Event Space",
    "Factory",
    "Fair",
    "Funeral Home",
    "Capitol Building",
    "City Hall",
    "Courthouse",
    "Embassy",
    "Consulate",
    "Fire Station",
    "Monument",
    "Landmark",
    "Police Station",
    "Town Hall",
    "Medical Center",
    "Dentist's Office",
    "Doctor's Office",
    "Emergency Room",
    "Hospital",
    "Laboratory",
    "Veterinarian Office",
    "Military Base",
    "Non-profit",
    "Office",
    "Ad Agency",
    "Campaign Office",
    "Conference Room",
    "Co-working Space",
    "Tech Startup",
    "Parking Structure",
    "Post Office",
    "Prison",
    "Radio Station",
    "Recruiting Agency",
    "School",
    "Circus School",
    "Driving School",
    "Elementary School",
    "Flight School",
    "High School",
    "Language School",
    "Middle School",
    "Music School",
    "Nursery School",
    "Preschool",
    "Private School",
    "Religious School",
    "Swim School",
    "Social Club",
    "Buddhist Temple",
    "Church",
    "Hindu Temple",
    "Monastery",
    "Mosque",
    "Prayer Room",
    "Shrine",
    "Synagogue",
    "Temple",
    "TV Station",
    "Voting Booth",
    "Warehouse"
    "Assisted Living Facility",
    "Home",
    "Housing Development",
    "Apartment Building",
    "Trailer Park",
    "ATM Lobby",
    "Adult Boutique",
    "Antique Shop",
    "Arts & Crafts Store",
    "Astrologer",
    "Auto Garage",
    "Automotive Shop",
    "Baby Store",
    "Bank",
    "Betting Shop",
    "Big Box Store",
    "Ikea",
    "Bike Shop",
    "Board Shop",
    "Booktsore",
    "Bridal Shop",
    "Camera Store",
    "Candy Store",
    "Car Dealership",
    "Car Wash",
    "Carpet Store",
    "Check Cashing Store",
    "Chocolate Shop",
    "Christmas Market",
    "Clothing Store",
    "Shoe Store",
    "Comic Shop",
    "Convenience Store",
    "Cosmetics Shop",
    "Costume Shop",
    "Credit Union",
    "Daycare",
    "Department Store",
    "Design Studio",
    "Discount Store",
    "Dive Shop",
    "Drugstore",
    "Pharmacy",
    "Dry Cleaner",
    "EV Charging Station",
    "Electronics Store",
    "Fabric Shop",
    "Fishing Tackle Shop",
    "Flea Market",
    "Flower Shop",
    "Beer Distributor",
    "Butcher Shop",
    "Cheese Shop",
    "Farmers Market",
    "Fish Market",
    "Food Court",
    "Grocery Store",
    "Health Food Store",
    "Liquor Shop",
    "Organic Grocery",
    "Street Food Stall",
    "Supermarket",
    "Wine Shop",
    "Frame Store",
    "Furniture Store",
    "Gaming Cafe",
    "Garden Center",
    "Gas Station",
    "Garage",
    "Gift Shop",
    "Gun Range",
    "Fitness Center",
    "Boxing Gym",
    "Climbing Gym",
    "Cycle Studio",
    "Dojo",
    "Yoga Studio",
    "Hardware Store",
    "Spa",
    "Hobby Shop",
    "IT Services Building",
    "Internet Cafe",
    "Jewelry Store",
    "Knitting Store",
    "Laundromat",
    "Laundry Service",
    "Leather Goods Store",
    "Locksmith",
    "Lottery Retailer",
    "Luggage Store",
    "Mall",
    "Marijuana Dispensary",
    "Market",
    "Massage Studio",
    "Mattress Store",
    "99¢ Shop",
    "Mobile Phone Store",
    "Record Store",
    "Nail Salon",
    "Newsstand",
    "Optics Shop",
    "Outdoor Outfitters Store",
    "Outlet Store",
    "Office Supplies Store",
    "Pawn Shop",
    "Pet Store",
    "Photo Lab",
    "Piercing Pagoda",
    "Pop-up Shop",
    "Print Shop",
    "Real Estate Office",
    "Recording Studio",
    "Recycling Facility",
    "Salon",
    "Barbershop",
    "Shipping Store",
    "Cobbler",
    "Smoke Shop"
    "Head Shop",
    "Smoothie Shop",
    "Souvenir Shop",
    "Tanning Salon",
    "Tattoo Parlor",
    "Thrift Store",
    "Vintage Store",
    "Toy Store",
    "Travel Agency",
    "Used Bookstore",
    "Videogame Store",
    "Video Store",
    "Watch Repair Shop",
    "Airport",
    "Airport Lounge",
    "Terminal",
    "Plane",
    "Boat",
    "Ferry",
    "Bus Station",
    "Bus Stop",
    "Cable Car",
    "Hotel",
    "Bed & Breakfast",
    "Hostel",
    "Hotel Pool",
    "Motel",
    "Resort",
    "Roof Deck",
    "Pier",
    "RV Park",
    "Rest Area",
    "Rental Car Office",
    "Subway",
    "Taxi Stand",
    "Toll Booth",
    "Toll Plaza",
    "Tourist Information Center",
    "Train Station",
    "Tram",
    "Travel Lounge",
    "Tunnel"
]

function preload(){
  //mariofont = loadFont("assets/mariofont.ttf")
  bg = loadImage("assets/background.jpg");
}

function setup() {
  createCanvas(800, 600);
  background(bg);
  

  //fill(255).strokeWeight(0).textSize(48);
  //textFont(mariofont);
  //text("Thank you " + name[random(399)] + " !",220,200);
 // text("But Our " + princess[random(119)] + " Is In",100,300);
  //text("Another " + location[random(507)] + " !",100,380);
}